name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_HOST_KEY_CHECKING: False
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
      # Clone Repo
      - uses: actions/checkout@v3

      - name: Install Python Packages
        run: |
          . /opt/pipx/venvs/ansible-core/bin/activate
          /opt/pipx/venvs/ansible-core/bin/python -m pip install boto3 botocore

      - name: Generate SSH Key From Secret
        run: |
          echo ${{ secrets.ANSIBLE_SSH_KEY }} > ansible_key 
          chmod 400 ansible_key

      - name: Test Inventory
        run: ansible --private-key=ansible_key -i aws_ec2.yml -m ping all 
